basic:
  task    : classification
  dataset : MFTP
  split   : False
  pretrain_path: 'results/pretrain/fold1_batch128_epoch200/best_model_state_dict.pt'


loss_fn:
  loss    : 'NT_Xent'

model:  
  input_channel: 1600
  output_channel: 21

train_params:
  fold      : 1
  batch     : 64
  epoch     : 1
  lr        : 0.001
  weight_decay: 0.0001
  temperature: 0.1

r_savepath:
  path: 'results/${ds.basic.dataset}/fold${ds.train_params.fold}_batch${ds.train_params.batch}_epoch${ds.train_params.epoch}'








  