basic:
  task    : classification
  dataset : MFTP
  split   : False
  pretrain_path: 'results/pretrain/fold1_batch128_epoch200/best_model_state_dict.pt'

model:  
  input_channel: 1600
  output_channel: 21

train_params:
  fold      : 1
  batch     : 128
  epoch     : 200
  lr        : 0.0001
  weight_decay: 0.0001
  temperature: 0.1

r_savepath:
  path: 'results/${ds.basic.dataset}/fold${ds.train_params.fold}_batch${ds.train_params.batch}_epoch${ds.train_params.epoch}_lr${ds.train_params.lr}'








  